main: codes.zucker.DeathChest.Main
name: DeathChest
version: 1.0
api-version: 1.15
commands:
  deathchest:
    description: Teleports you to active deathchests
    usage: /deathchest [player]
    permission: DeathChest.tp
    permission-message: You don't have permission for that.